### ISSUE TITLE
EISDIR: illegal operation on a directory, fstat ($.isFIFO)

### ISSUE THREAD

**Issue by jaandrle** [jaandrle/nodejsscript#42]
**Describe the bug:**

https://github.com/nodejs/node/issues/19831

**Technical background (following information can be really helpful 👍):**
 - OS: Windows
 - nodejs: 18

**Additional context:**
```
Error: EISDIR: illegal operation on a directory, fstat
code: 1
stack:
    at fstatSync (node:fs:1492:3)
    at Array.isFIFO (file:///C:/Users/jirin/Documents/GitHub/DGF-Certified-Supervisory-Academy/build/node_modules/nodejsscript/src/$.js:27:31)
    at Object.[stdin] (file:///C:/Users/jirin/Documents/GitHub/DGF-Certified-Supervisory-Academy/build/node_modules/nodejsscript/src/$.js:41:11)
    at main (file:///C:/Users/jirin/Documents/GitHub/DGF-Certified-Supervisory-Academy/build/node_modules/nodejsscript/bin/index.mjs:40:26)
    at file:///C:/Users/jirin/Documents/GitHub/DGF-Certified-Supervisory-Academy/build/node_modules/nodejsscript/bin/index.mjs:55:3
```

**Comment by jaandrle** [comment]
This is node thing, but since v1.0.3 it shouldn’t block execution of njs. (see https://github.com/jaandrle/nodejsscript/releases/tag/v1.0.3)
